### ISSUE TITLE
Tone of introduction and documentation refresh

### ISSUE THREAD

**Issue by elsassph** [MatthijsKamstra/haxejs#21]
Hello, I've looked again at this documentation, and I think there are many good things here and it has potential to be a friendly introduction, however, although I appreciate it lives under your github account, I think the tone in the introduction parts doesn't feel very professional: there's too much ranting and rather personal feelings which could be better hosted under a "contributors" section.

Would you accept PRs to make this book more formal (and maybe up to date)?

**Comment by MatthijsKamstra** [comment]
It was written 2 years ago out of frustration...

I am better now, so ABSOLUTELY

(and my 5cents can be removed)

**Comment by markknol** [comment]
And would be nice to use a spellchecker too 😊 
Personally I would love to have all such examples/tutorials in the cookbook :D

**Comment by MatthijsKamstra** [comment]
@markknol funny enough most of it is written with spellings check :(

and sure, just point me in the right direction and I will look into it!

**Comment by markknol** [comment]
Ill open issue with some stuff I found, no problem!
