### ISSUE TITLE
Spelling 

### ISSUE THREAD

**Issue by markknol** [MatthijsKamstra/haxejs#23]
https://matthijskamstra.github.io/haxejs/09expose/about.html
* Manuel > Manual
* `@expose`  > `@:expose`
* Also good to mention that you can do `@:native("GiveItAnotherName")` to rewrite the package/classname

https://github.com/MatthijsKamstra/haxejs/search?utf8=%E2%9C%93&q=jquary&type=
JQuary > JQuery 

https://github.com/MatthijsKamstra/haxejs/search?utf8=%E2%9C%93&q=heightlight+&type=
heightlight > highlight

https://github.com/MatthijsKamstra/haxejs/search?utf8=%E2%9C%93&q=usefull++&type=
usefull > useful

**Comment by MatthijsKamstra** [comment]
thx, 

I didn't know that (`@:native`), not really a surprise but didn't know.
 
 Btw you can change the markdown as well... might speed stuff up a bit ??

**Comment by markknol** [comment]
Top!
