### ISSUE TITLE
02dom/example.html

### ISSUE THREAD

**Issue by russell52** [MatthijsKamstra/haxejs#7]
Now try the VanillaJS version:

```
var p = document.createParagraphElement();
p.innerText = 'VanillaJs DOM ready';

document.querySelector(".container").appendChild(p);
```

});

In the last line of code: 

querySelector(".container")

should be removed.

**Comment by MatthijsKamstra** [comment]
Ah at first I thought you are right, but now I see I need to explain it better...
So thanks for pointing it out to me

**Comment by MatthijsKamstra** [comment]
I have adjusted the files, thx again for pointing it out!
